### ISSUE TITLE
Create generic error pages for 404 and 500

### ISSUE THREAD

**Issue by mamchenkov** [QoboLtd/project-template#53]
We could benefit from having generic error pages for 404 and 500, with relevant Nginx configuration.  This would make our occasional uncaught PHP exceptions and 502 bad gateways not as annoying as they are.

**Comment by flangofas** [comment]
Related PR: https://github.com/QoboLtd/project-template/pull/54

**Comment by mamchenkov** [comment]
Done and tagged as v1.0.15

**Comment by flangofas** [comment]
:+1:
